update

diff --git a/JavaApp/Makefile b/JavaApp/Makefile
--- a/JavaApp/Makefile
+++ b/JavaApp/Makefile
@@ -13,6 +13,16 @@ JCFLAGS := -cp "$(subst $() $(),:,$(wildcard $(SOURCEDIR)/*/):$(wildcard libs/*/
 
 all: $(TARGETS)
 
+# Sometimes the CI produces empty class file resulting in broken jar, so we check and abort here
+check_empty_classes:
+	@set -e
+	@echo "Checking for empty class files"
+	$(eval EMPTY_CLASSES := $(shell find $(OUTPUTDIR) -name '*.class' -size 0))
+	@if [ -n "$(EMPTY_CLASSES)" ]; then \
+		echo "Error: found empty class files in $@: $(EMPTY_CLASSES)"; \
+		exit 1; \
+	fi
+
 # Rules for building java class
 $(CLASSES): $(OUTPUTDIR)/%.class: $(SOURCEDIR)/%.java
 	@set -e
